# Generated by Django 4.2.1 on 2024-11-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_populaer',
            field=models.BooleanField(default=False),
        ),
    ]
