# Generated by Django 4.2.1 on 2024-11-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_blog_is_populaer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_populaer',
        ),
    ]
